# Generated by Django 2.1.1 on 2018-09-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0002_auto_20180911_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(default=1, max_length=4),
        ),
    ]
