# Generated by Django 2.1.1 on 2018-09-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0003_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manager',
            field=models.CharField(default='暂无', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='createUser',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='inChargeUser',
            field=models.IntegerField(),
        ),
    ]
