# Generated by Django 2.1.1 on 2018-09-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('create_user', models.IntegerField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('precondition', models.TextField(default='', max_length=255)),
                ('steps', models.TextField()),
                ('expect', models.TextField()),
                ('create_user', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('last_edit_user', models.IntegerField()),
                ('last_edit_time', models.DateTimeField()),
                ('case_module', models.IntegerField()),
                ('editable', models.BooleanField(default=True)),
            ],
        ),
    ]
