# Generated by Django 2.1.1 on 2018-09-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('testcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
