# Generated by Django 2.1.1 on 2018-09-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('testcase', '0002_auto_20180914_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='precondition',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
