# Generated by Django 2.1.1 on 2018-09-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('testcase', '0003_auto_20180919_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='last_edit_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
