# Generated by Django 2.0.5 on 2018-09-20 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('testcase', '0003_auto_20180919_2226'),
        ('testcase', '0004_auto_20180919_1726'),
    ]

    operations = [
    ]
