# Generated by Django 2.1.1 on 2018-09-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('last_login_time', models.DateTimeField()),
                ('create_time', models.DateTimeField()),
                ('privilege', models.IntegerField()),
                ('email', models.EmailField(default='<django.db.models.fields.CharField>@mail.jj.cn', max_length=254)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
